### ISSUE TITLE
Publish package updates to NPM

### ISSUE THREAD

**Issue by varanauskas** [wbobeirne/eth-balance-checker#23]
Package has received multiple updates to the `master` branch, however, the latest version on NPM is published more than 3 years ago.

Please publish the changes to NPM manually, or work on a solution to automatically publish them on GitHub release (and start making releases)

**Comment by wbobeirne** [comment]
Absolutely, open to PRs on this and I can add an NPM token to the repo so that it'll publish the updates. Would prefer a GitHub action. I can also possibly hit this in a bit.

**Comment by dandv** [comment]
Might the old package used be why [the demo fails](https://github.com/wbobeirne/eth-balance-checker-demo/issues)?

**Comment by wbobeirne** [comment]
No, but I do need to update this. My bad.
