### ISSUE TITLE
Move truffle to devDependencies

### ISSUE THREAD

**Issue by varanauskas** [wbobeirne/eth-balance-checker#24]
As I understand `truffle` is only required for development/testing of the solidity contract.

As users querying the balance on one of the supported networks query an already deployed contract directly, they do not require `truffle`.

Thus, truffle could be migrated to `devDependencies`

**Comment by wbobeirne** [comment]
Yep, no idea why this was in there. Worst case it should be a `peerDependency`, ala #15, but I think it can just be a devDependency.

**Comment by dandv** [comment]
Would be nice to download as few dependencies as possible. The more deps, the higher the risk of supply chain attacks.

The Medium post says "The library also defaults to using a contract that’s already been deployed on mainnet", so yay.
