### ISSUE TITLE
NICE tool, could you add more methods to get symbol and decimals?

### ISSUE THREAD

**Issue by OU8N** [wbobeirne/eth-balance-checker#48]
NICE tool, could you add more methods to get symbol and decimals?

**Comment by wbobeirne** [comment]
There are projects that maintain up-to-date token list JSON files, such as https://github.com/ethereum-lists/tokens, so I'm going to consider this out of scope for the project. You can easily feed the addresses from there into eth-balance-checker.

**Comment by OU8N** [comment]
> There are projects that maintain up-to-date token list JSON files, such as https://github.com/ethereum-lists/tokens, so I'm going to consider this out of scope for the project. You can easily feed the addresses from there into eth-balance-checker.

@wbobeirne Thanks for your advice. I found this [https://github.com/trustwallet/assets](https://github.com/trustwallet/assets).
