### ISSUE TITLE
Simple GUI for quick usage

### ISSUE THREAD

**Issue by varanauskas** [wbobeirne/eth-balance-checker#50]
I've made a stupid simple GUI for eth-balance-checker for my for my own quick usage

Thought I might share it here if anyone else would like to use it

https://varanauskas.github.io/eth-balance-checker-gui/
(Repo/source: https://github.com/varanauskas/eth-balance-checker-gui)

**Comment by wbobeirne** [comment]
Very cool, thanks for sharing! Since this isn't really an actionable issue though, I'm going to close it.
