### ISSUE TITLE
Issue running npm install

### ISSUE THREAD

**Issue by Crack019** [wbobeirne/eth-balance-checker#54]
src/ethers.ts:7:31 - error TS2307: Cannot find module './abis/BalanceChecker.abi.json' or its corresponding type declarations.

Extracted zip and trying to install using NPM.

[2022-12-21T23_46_09_767Z-debug-0.log](https://github.com/wbobeirne/eth-balance-checker/files/10282526/2022-12-21T23_46_09_767Z-debug-0.log)

**Comment by Crack019** [comment]
[2022-12-22T00_05_54_261Z-debug-0.log](https://github.com/wbobeirne/eth-balance-checker/files/10282605/2022-12-22T00_05_54_261Z-debug-0.log)
[2022-12-22T00_05_54_261Z-debug-0.log](https://github.com/wbobeirne/eth-balance-checker/files/10282600/2022-12-22T00_05_54_261Z-debug-0.log)
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

> eth-balance-checker@0.2.0 build:lib
> tsc

src/ethers.ts:7:31 - error TS2307: Cannot find module './abis/BalanceChecker2.abi.json' or its corresponding type declarations.

7 import BalanceCheckerABI from './abis/BalanceChecker2.abi.json';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/ethers.ts:7

npm ERR! code 2
npm ERR! path /root/eth-balance-checker-master
npm ERR! command failed
npm ERR! command sh -c npm run build

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-12-22T00_05_54_261Z-debug-0.log

**Comment by wbobeirne** [comment]
Hey @Crack019, what OS are you on? The `abis` folder in `src` is just a symlink so it's very likely something about either your OS or the way you cloned the repo doesn't like symlinks.

**Comment by wbobeirne** [comment]
Also the readme should probably remove suggesting using `npm install` for development, you should use `yarn` so that it respects the `yarn.lock` file for dependencies.

**Comment by Crack019** [comment]
I'm using Debian 11, fixed error using GitHub CLI and yarn install, thanks [wbobeirne](https://github.com/wbobeirne)
