### ISSUE TITLE
address for kovan

### ISSUE THREAD

**Issue by liangwu** [wbobeirne/eth-balance-checker#9]
0x55ABBa8d669D60A10c104CC493ec5ef389EC92bb

I depoly it on to kovan chain for use

**Comment by varanauskas** [comment]
I have also successfully verified that the contract source code matches:
https://kovan.etherscan.io/address/0x55ABBa8d669D60A10c104CC493ec5ef389EC92bb#code

**Comment by liangwu** [comment]
and also:
polygon mainnet(137): 0x2352c63A83f9Fd126af8676146721Fa00924d7e4
polygon testnet(80001): 0x2352c63A83f9Fd126af8676146721Fa00924d7e4
BSC mainnet(56): 0x2352c63A83f9Fd126af8676146721Fa00924d7e4
BSC testnet(97): 0x2352c63A83f9Fd126af8676146721Fa00924d7e4

**Comment by varanauskas** [comment]
I've deployed BSC Mainnet and Testnet too at #18 

I can open a PR for polygon mainnet and testnet

**Comment by varanauskas** [comment]
@liangwu could you provide the solc version used for contract compilation so I could verify their source code?
https://polygonscan.com/address/0x2352c63A83f9Fd126af8676146721Fa00924d7e4#code

**Comment by liangwu** [comment]
> @liangwu could you provide the solc version used for contract compilation so I could verify their source code? (Or verify the source code yourself)
> https://polygonscan.com/address/0x2352c63A83f9Fd126af8676146721Fa00924d7e4#code

pragma solidity ^0.4.21;

**Comment by varanauskas** [comment]
@liangwu I am having some trouble verifying it on polygonscan, it throws this error
`Compiler debug log:
 Error! Unable to generate Contract ByteCode and ABI (Compiler Exception)
 For troubleshooting, you can try compiling your source code with the Remix - Solidity IDE and check for exceptions

Compiler Warning(s):

myc:12:5: TypeError: Wrong argument count for function call: 1 arguments given but expected 0.
    revert("BalanceChecker does not accept payments")
    ^-----------------------------------------------^ `
Could you try verifying it yourself here: https://polygonscan.com/address/0x2352c63A83f9Fd126af8676146721Fa00924d7e4#code

**Comment by liangwu** [comment]
done

Tadas Varanauskas ***@***.***> 于2021年8月23日周一 下午4:54写道：
